"'Development Environment' As screen":
    LoadingSpinnerColor: =RGBA(100, 118, 132, 1)

    Header_7 As Header:

    LeftNav_7 As LeftNav:
        MenuItems: =colMenu
        Width: =LeftNav_7.MenuWidth
        Y: =Header_7.Height
        ZIndex: =2

