"'Development Environment' As screen":
    Fill: =RGBA(255,255,255,1)
    LoadingSpinnerColor: =RGBA(211, 66, 9, 1)

    Header_7 As Header:

    LeftNav_7 As LeftNav:
        MenuItems: =colMenu
        Width: =LeftNav_7.MenuWidth
        Y: =Header_7.Height
        ZIndex: =2

